name: Linting

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.8", "3.9", "3.10"]
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}
          cache: pip
      - uses: psf/black@stable
        with:
          options: "--check --verbose"
          src: "."
          version: "21.5b1"
      - run: python -m pip install --upgrade pip
      - run: pip install pylint
      - name: Analysing the code with pylint
        run: |
          pylint $(git ls-files '*.py')
