#
# SAMPLE docker-compose for deploying LARA's legend-and-map segmentation pipeline
#
version: '3.8'
services:

    #---- Legend Map Segmenter
    legend-map-segmenter:
        container_name: legend-map-segmenter
        image: docker.uncharted.software/lara/segmenter:0.1
        env_file:
            - ./.env
        networks:
            - lara_pipeline
        ports:
            - 5001:5000
        restart: on-failure
        command: "python ./run_app.py"

        volumes:
            - segmenter_data_cache:${LOCAL_DATA_CACHE}

networks:
    lara_pipeline:
