[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "lara-tasks"
version = "0.1.0"
description = "LARA pipeline tasks"
readme = "README.md"
dependencies = [
    "numpy",
    "tqdm",
    "pydantic",
    "tiktoken",
    "openai",
    "google-cloud-vision",
    "grpcio",
    "boto3",
    "pillow",
    "geopy",
    "matplotlib",
    "opencv-python",
    "protobuf",
    "scikit_image",
    "scikit_learn",
    "Shapely",
    "utm",
    "torch", # needed for detectron2, but not listed in its dependencies (see setup.py in detectron2 for reasons)
    "torchvision",
    "detectron2 @ git+https://github.com/facebookresearch/detectron2.git"
]

[tool.setuptools.packages]
find = {}
