[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "lara-utils"
version = "0.1.0"
description = "LARA utilities"
readme = "README.md"
dependencies = [
    "rasterio",
    "pandas",
    "numpy",
    "osgeo"
]

[tool.setuptools.packages]
find = {}
