name: Linting

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.9"]
    steps:
      - name: Checkout source code
        uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
          cache: "pip"
          cache-dependency-path: "**/pyproject.toml"
      - name: Check formatting
        uses: psf/black@stable
        with:
          options: "--check --verbose --exclude='tasks/segmentation/(layoutlmft|ditod)' --extend-exclude='build/lib'"
          src: "."
          version: ">=22.3"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install torch==2.0.1
          pip install ./tasks
          pip install ./pipelines/segmentation
          pip install ./pipelines/text_extraction
          pip install ./pipelines/metadata_extraction
          pip install ./pipelines/geo_referencing
      - name: Pyright Type checking
        uses: jakebailey/pyright-action@v1
        with:
          pylance-version: latest-release
          project: pyrightconfig.json
